17 calculation nodes
135 radks were output, 1 radks were filtered out
0 nodes(0%%) have bij sum + bij inactive < .9
7 nodes(41%%) have bij sum + bij_inact > 1.1
    Caused by not enough rays or from overlapping surfaces, Max Value= 1.214456 for PLUS_Y.1201
5000 average number of rays per node shot
2 nodes(11%%) have Bij Inactive > .2
    This may be ok, but may be an indication of an incorrect active side
 
